# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: florianweich.me
email: hallo@florianweich.me
description: >
  Florian Weich. Designer. Webentwickler.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://florianweich.me" # the base hostname & protocol for your site
#twitter_username: florianweich
#github_username:  florianweich

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - octopress-autoprefixer
exclude: [node_modules, gulpfile.js, bower_components, Gemfile, Gemfile.lock, package.json, js/scripts.js]
collections:
  - html_tools_frameworks
  - education_career
  - skills_languages
  - references
